id_field:
  name:        name
  label:       Bezeichnung
  placeholder: "z.B. arch-builder"
  max:         100

fields:
  - name:        tag
    label:       Tag
    type:        text
    placeholder: "latest"
    max:         50
