id_field:
  name:        name
  label:       Paketname
  placeholder: "z.B. my-package"
  max:         100

fields:
  - name:        source_url
    label:       AUR Git-URL
    type:        text
    placeholder: "https://aur.archlinux.org/my-package.git"
    max:         500
