label:           Pakete
nav_group:       Pakete
settings_button: false

card_actions:
  - type: run
  - type: log
  - type: open_url
    url: "https://aur.archlinux.org/packages/{item}"
    hide_if_field_value:
      field: typ
      value: custom
